import { AppException } from '#exceptions/app_exception'

export class NotFoundException extends AppException {
  constructor(resource: string = 'Recurso') {
    super(`${resource} n√£o encontrado`, 404, 'E_NOT_FOUND')
  }
}
